### ISSUE TITLE
Print Screen shortcut is invalid.

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-settings-daemon#10]
Print Screen快捷键无效

**Comment by shang-xiaoyang** [comment]
在最新版本ukui-settings-daemon中，调用的是gnome-screenshort，而系统中装的是mate-screenshort安装包，将gnome-screenshort软件包安装即可。

**Comment by ikeyhzj** [comment]
http://192.168.6.179/zentao/bug-view-4096.html
